# Generated by Django 3.2 on 2021-04-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('artist', models.URLField()),
                ('tracks', models.URLField()),
                ('myself', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('identificador', models.CharField(max_length=200)),
                ('albums', models.URLField()),
                ('tracks', models.URLField()),
                ('myself', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identificador', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist', models.URLField()),
                ('album', models.URLField()),
                ('myself', models.URLField()),
                ('album_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music_app.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='music_app.artist'),
        ),
    ]
