# Generated by Django 3.2 on 2021-05-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='self',
            new_name='myself',
        ),
    ]
