# Generated by Django 3.2 on 2021-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_rename_self_artist_myself'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='self',
            new_name='myself',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='self',
            new_name='myself',
        ),
    ]
