# Generated by Django 3.2 on 2021-04-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_carspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('artist', models.URLField()),
                ('tracks', models.URLField()),
                ('myself', models.URLField()),
                ('artist_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='music_app.artist')),
            ],
        ),
    ]
